name: car_wash_app
description: A car wash application for both Android and iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  form_validator: ^2.1.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true